### ISSUE TITLE
Open config Schema form if config.json not contain plugin config

### ISSUE THREAD

**Issue by grzegorz914** [homebridge/plugin-ui-utils#3]
Hi,

after install this: https://github.com/grzegorz914/homebridge-xbox-tv#readme plugin and open its settings for first config the custom UI util is loaded but the button to Show/Hide Config doesn’t work and not open config.schema. If I add manually the config to the config.json the custom UI util work correct.

**Comment by thenewwazoo** [comment]
@grzegorz914 I recently went through something similar, and had to add [a routine to "bootstrap" the config](https://github.com/thenewwazoo/homebridge-lutron-caseta-leap/blob/main/homebridge-ui/public/index.html#L12). It's kinda ugly, but it gets the job done. I've found that users can't be relied upon to have a sane config when the UI starts up!

**Comment by grzegorz914** [comment]
I have fixed this, so close the issue.
