### ISSUE TITLE
How to extract properties of an object

### ISSUE THREAD

**Issue by uswong** [homebridge/plugin-ui-utils#7]
### Current Situation

Hi, I have a simple question.

I have the following config and while I can extract the AAIP within the <script> by

const pluginConfig = await homebridge.getPluginConfig();
const aaip = pluginConfig[0].AAIP;

How do I extract the ipAddress within the devices?

     {
         "name": "Advantage",
         "devices": [
             {
                 "name": "Aircon1",
                 "ipAddress": "192.168.0.31"
             },
             {
                 "name": "Aircon2",
                 "ipAddress": "192.168.0.173"
             }
         ],
         "platform": "Advantage",
        "AAIP": "192.168.2.222",
        "AAIP2": "127.0.0.1",
        "AAIP3": "10.1.1.20"
     }

### Logs

```markdown
No log
```

### Configuration

```json
{
    "name": "Advantage",
    "devices": [
        {
            "name": "Aircon1",
            "ipAddress": "192.168.0.31"
        },
        {
            "name": "Aircon2",
            "ipAddress": "192.168.0.173"
        }
    ],
    "platform": "Advantage",
    "AAIP": "192.168.2.222",
    "AAIP2": "127.0.0.1",
    "AAIP3": "10.1.1.20"
}
```

### Environment

- OS: Raspbian GNU/Linux Bullseye (11)
- Software: homebridge-ui
- Node: v16.15.1
- npm: v8.15.1

### Process Supervisor

hb-service

**Comment by oznu** [comment]
`devices` is an array.

```js
const pluginConfig = await homebridge.getPluginConfig();
const ip = pluginConfig.devices[0].ipAddress
```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array

**Comment by uswong** [comment]
Thanks but it did not work as is.

I did a bit of trial-and-error and got it working with:

     const pluginConfig = await homebridge.getPluginConfig();
     const ip1 = pluginConfig[0].devices[0].ipAddress
     const ip2 = pluginConfig[0].devices[1].ipAddress
